import Background from "@/components/Layout/Background";
import Container from "@/components/Layout/Container";
import LoginButton from "@/components/common/LoginButton";
import { saveStorage } from "@/lib/storage";
import { Box } from "@chakra-ui/react";
import Head from "next/head";
import { useEffect } from "react";

export default function Home() {
  useEffect(() => {
    const token = process.env.NEXT_PUBLIC_TOKEN ?? "";
    saveStorage("token", token);
  }, []);
  return (
    <>
      <Head>
        <title>스피릿로그</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Background color="#000" />
        <Box></Box>
        <LoginButton />
      </Container>
    </>
  );
}
